channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - aiohttp=3.7.4.post0
  - appdirs=1.4.4
  - astor=0.8.1
  - astroid=2.4.1
  - async-timeout=3.0.1
  - attrs=19.3.0
  - autopep8=1.4.4
  - backcall=0.1.0
  - biopython=1.77
  - blas=1.0
  - bleach=3.1.4
  - blinker=1.4
  - c-ares=1.18.1
  - ca-certificates=2020.1.1
  - cachetools=4.2.2
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - conda-pack=0.4.0
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - future=0.18.2
  - gast=0.2.2
  - glib=2.63.1
  - gmp=6.1.2
  - google-auth=1.28.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.9
  - idna_ssl=1.1.0
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.4
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.2
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - more-itertools=8.3.0
  - multidict=5.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - nose=1.3.7
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - py=1.8.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=2.0.1
  - pylint=2.5.2
  - pymysql=0.9.3
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.2
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyutilib=5.8.0
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rope=0.17.0
  - rsa=4.7.2
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - tensorboard-plugin-wit=1.6.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.4
  - tqdm=4.63.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.1.7
  - yarl=1.6.3
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - beautifulsoup4==4.11.2
    - fancycompleter==0.9.1
    - grpcio==1.29.0
    - gurobipy==9.1.2
    - importlib-resources==5.4.0
    - ipdb==0.13.11
    - ipython==7.16.3
    - jupytext==1.5.0
    - mhcflurry==1.4.3
    - mhcnames==0.4.8
    - mhcnuggets==2.3.2
    - np-utils==0.5.12.1
    - opt-einsum==3.2.1
    - pdbpp==0.10.3
    - protobuf==3.12.2
    - pyomo==5.6.9
    - pyrepl==0.9.0
    - pyvcf==0.6.8
    - pyvcf3==1.0.3
    - soupsieve==2.3.2.post1
    - tensorboard==1.15.0
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - tomli==1.2.3
    - wmctrl==0.4
    - git+https://github.com/KohlbacherLab/epytope

